# Generated by Django 6.1 on 2026-08-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='genres/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('youtube_url', models.URLField(max_length=500)),
                ('youtube_video_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='movies/thumbnails/')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='movies/backdrops/')),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('duration', models.CharField(default='2h 00m', help_text='e.g. 2h 15m', max_length=50)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('writers', models.CharField(blank=True, max_length=255)),
                ('cast', models.TextField(blank=True, help_text='Comma-separated cast members')),
                ('language', models.CharField(default='English', max_length=100)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('rating', models.DecimalField(db_index=True, decimal_places=1, default=7.5, max_digits=3)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('is_popular', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
